parameters:
#    iqa_crowd_sourcing.example.class: Iqa\CrowdSourcingBundle\Example

services:
#    iqa_crowd_sourcing.example:
#        class: %iqa_crowd_sourcing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
