<?php

namespace Proxies\__CG__\Iqa\CrowdSourcingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class conditions extends \Iqa\CrowdSourcingBundle\Entity\conditions implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'filename', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'originalId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'parameterName', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'parameterValue');
        }

        return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'filename', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'originalId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'parameterName', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\conditions' . "\0" . 'parameterValue');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (conditions $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilename($filename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilename', array($filename));

        return parent::setFilename($filename);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilename', array());

        return parent::getFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalId($originalId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalId', array($originalId));

        return parent::setOriginalId($originalId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalId', array());

        return parent::getOriginalId();
    }

    /**
     * {@inheritDoc}
     */
    public function setParameterName($parameterName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParameterName', array($parameterName));

        return parent::setParameterName($parameterName);
    }

    /**
     * {@inheritDoc}
     */
    public function getParameterName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParameterName', array());

        return parent::getParameterName();
    }

    /**
     * {@inheritDoc}
     */
    public function setParameterValue($parameterValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParameterValue', array($parameterValue));

        return parent::setParameterValue($parameterValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getParameterValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParameterValue', array());

        return parent::getParameterValue();
    }

}
