<?php

namespace Proxies\__CG__\Iqa\CrowdSourcingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class sessionsRatings extends \Iqa\CrowdSourcingBundle\Entity\sessionsRatings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'sessionId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'positionInSession', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'stimulusId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'ratingValue', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'ratingDuration', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'isOrig', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'trainingMode', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'hiddenRef');
        }

        return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'sessionId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'positionInSession', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'stimulusId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'ratingValue', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'ratingDuration', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'isOrig', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'trainingMode', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\sessionsRatings' . "\0" . 'hiddenRef');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (sessionsRatings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSessionId($sessionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessionId', array($sessionId));

        return parent::setSessionId($sessionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSessionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessionId', array());

        return parent::getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPositionInSession($positionInSession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPositionInSession', array($positionInSession));

        return parent::setPositionInSession($positionInSession);
    }

    /**
     * {@inheritDoc}
     */
    public function getPositionInSession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositionInSession', array());

        return parent::getPositionInSession();
    }

    /**
     * {@inheritDoc}
     */
    public function setStimulusId($stimulusId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStimulusId', array($stimulusId));

        return parent::setStimulusId($stimulusId);
    }

    /**
     * {@inheritDoc}
     */
    public function getStimulusId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStimulusId', array());

        return parent::getStimulusId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRatingValue($ratingValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRatingValue', array($ratingValue));

        return parent::setRatingValue($ratingValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getRatingValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRatingValue', array());

        return parent::getRatingValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setRatingDuration($ratingDuration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRatingDuration', array($ratingDuration));

        return parent::setRatingDuration($ratingDuration);
    }

    /**
     * {@inheritDoc}
     */
    public function getRatingDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRatingDuration', array());

        return parent::getRatingDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOrig($isOrig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOrig', array($isOrig));

        return parent::setIsOrig($isOrig);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOrig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOrig', array());

        return parent::getIsOrig();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrainingMode($trainingMode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrainingMode', array($trainingMode));

        return parent::setTrainingMode($trainingMode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrainingMode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrainingMode', array());

        return parent::getTrainingMode();
    }

    /**
     * {@inheritDoc}
     */
    public function getHiddenRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHiddenRef', array());

        return parent::getHiddenRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setHiddenRef($hiddenRef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHiddenRef', array($hiddenRef));

        return parent::setHiddenRef($hiddenRef);
    }

}
