<?php

namespace Proxies\__CG__\Iqa\CrowdSourcingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class experiment extends \Iqa\CrowdSourcingBundle\Entity\experiment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'name', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'procedureId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'numRepetitions', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'welcomeMessage', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'surveyTitle', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'preSurveyText', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'presentationDuration', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'labCondition');
        }

        return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'name', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'procedureId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'numRepetitions', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'welcomeMessage', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'surveyTitle', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'preSurveyText', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'presentationDuration', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\experiment' . "\0" . 'labCondition');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (experiment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcedureId($procedureId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcedureId', array($procedureId));

        return parent::setProcedureId($procedureId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcedureId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcedureId', array());

        return parent::getProcedureId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumRepetitions($numRepetitions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumRepetitions', array($numRepetitions));

        return parent::setNumRepetitions($numRepetitions);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumRepetitions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumRepetitions', array());

        return parent::getNumRepetitions();
    }

    /**
     * {@inheritDoc}
     */
    public function setWelcomeMessage($welcomeMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWelcomeMessage', array($welcomeMessage));

        return parent::setWelcomeMessage($welcomeMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getWelcomeMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWelcomeMessage', array());

        return parent::getWelcomeMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurveyTitle($surveyTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurveyTitle', array($surveyTitle));

        return parent::setSurveyTitle($surveyTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurveyTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurveyTitle', array());

        return parent::getSurveyTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreSurveyText($preSurveyText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreSurveyText', array($preSurveyText));

        return parent::setPreSurveyText($preSurveyText);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreSurveyText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreSurveyText', array());

        return parent::getPreSurveyText();
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentationDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentationDuration', array());

        return parent::getPresentationDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentationDuration($presentationDuration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentationDuration', array($presentationDuration));

        return parent::setPresentationDuration($presentationDuration);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabCondition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabCondition', array());

        return parent::getLabCondition();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabCondition($labCondition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabCondition', array($labCondition));

        return parent::setLabCondition($labCondition);
    }

}
