<?php

namespace Proxies\__CG__\Iqa\CrowdSourcingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class user extends \Iqa\CrowdSourcingBundle\Entity\user implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'genderId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'age', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'colortest', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'vision', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'displayHeight', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'viewingDistance', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'expert', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'personalID');
        }

        return array('__isInitialized__', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'id', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'genderId', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'age', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'colortest', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'vision', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'displayHeight', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'viewingDistance', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'expert', '' . "\0" . 'Iqa\\CrowdSourcingBundle\\Entity\\user' . "\0" . 'personalID');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (user $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenderId($genderId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenderId', array($genderId));

        return parent::setGenderId($genderId);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenderId', array());

        return parent::getGenderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', array($age));

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', array());

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setVision($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVision', array($value));

        return parent::setVision($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getVision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVision', array());

        return parent::getVision();
    }

    /**
     * {@inheritDoc}
     */
    public function setColortest($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColortest', array($value));

        return parent::setColortest($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getColortest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColortest', array());

        return parent::getColortest();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayHeight', array());

        return parent::getDisplayHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayHeight($displayHeight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayHeight', array($displayHeight));

        return parent::setDisplayHeight($displayHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getViewingDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewingDistance', array());

        return parent::getViewingDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setViewingDistance($viewingDistance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViewingDistance', array($viewingDistance));

        return parent::setViewingDistance($viewingDistance);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpert', array());

        return parent::getExpert();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpert($expert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpert', array($expert));

        return parent::setExpert($expert);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonalID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonalID', array());

        return parent::getPersonalID();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonalID($personalID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonalID', array($personalID));

        return parent::setPersonalID($personalID);
    }

}
