<?php

namespace Iqa\CrowdSourcingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OriginalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OriginalRepository extends EntityRepository
{
}
