<?php

namespace Iqa\CrowdSourcingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ratingLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ratingLabelRepository extends EntityRepository
{
}
