<?php

namespace Iqa\CrowdSourcingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * stimuliInExperimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stimuliInExperimentRepository extends EntityRepository
{
}
